#!/usr/bin/env node
/*
 * Injects the dispersed annex vulnerabilities + decoy routes into a Juice Shop source clone.
 *   node install-annex.js /path/to/juice-shop
 * Idempotent; reverse with uninstall-annex.js.
 */
const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const dir = process.argv[2];
if (!dir) { console.error('Usage: node install-annex.js /path/to/juice-shop'); process.exit(1); }
const serverPath = path.join(dir, 'server.ts');
const routesDir = path.join(dir, 'routes');
if (!fs.existsSync(serverPath) || !fs.existsSync(routesDir)) {
  console.error(`Not a Juice Shop source clone: ${dir}\n(If you use the Docker image, clone from source instead: git clone https://github.com/juice-shop/juice-shop.git)`);
  process.exit(1);
}

const MODULES = [
  'productCatalog',
  'deliveryTracking',
  'accountManagement',
  'adminDiagnostics',
  'dataImport',
  'integrations',
  'promotions',
  'couponManager',
  'giftCards',
  'wishlist',
  'shippingCalculator',
  'returnProcessor',
  'affiliateTracker',
  'vendorPortal',
  'taxCalculator',
  'loyaltyPoints',
  'searchIndex',
  'cartDiscounts',
  'notificationsApi',
  'adminReports',
  'mobileApi',
  'feedbackCollector',
  'inventoryManager',
  'priceTracker',
  'orderExport',
  'sessionManager',
  'contentManager',
  'analyticsTracker',
  'reviewModeration',
  'customerSupport',
  'warehouseApi',
  'billingPortal',
  'subscriptionManager',
  'complianceAudit',
  'storeLocator',
  'recipeFinder',
  'loyaltyRewards',
  'subscriptionBilling',
  'customerProfiles',
  'productReviews',
  'orderTracking',
  'wishlistManager',
  'notificationCenter',
  'inventoryCheck',
  'promoCodes',
  'shippingZones',
  'returnsManager',
  'vendorManagement',
  'customerSupport2',
  'analyticsDashboard',
  'priceManager',
  'contentPages',
  'taxExemptions',
  'giftCardRegistry'
];
const IMPORTS = MODULES.map(m => `import * as ${m} from './routes/${m}'`);
const MOUNTS = [
  "  app.get('/rest/products/by-tag', productCatalog.productsByTag())",
  "  app.get('/rest/products/catalog', productCatalog.catalogListing())",
  "  app.post('/rest/products/:id/questions', productCatalog.postProductQuestion())",
  "  app.get('/rest/products/:id/questions', productCatalog.listProductQuestions())",
  "  app.get('/rest/products/bulk-lookup', productCatalog.bulkProductLookup())",
  "  app.get('/rest/delivery/track-external', deliveryTracking.trackExternal())",
  "  app.get('/rest/track/click', deliveryTracking.trackClick())",
  "  app.get('/rest/delivery/receipt', deliveryTracking.downloadReceipt())",
  "  app.get('/rest/delivery/tracking-history/:orderId', deliveryTracking.getTrackingHistory())",
  "  app.get('/rest/delivery/carriers', deliveryTracking.listCarriers())",
  "  app.get('/rest/user/notes/:id', accountManagement.getNote())",
  "  app.put('/rest/user/notes/:id', accountManagement.updateNote())",
  "  app.post('/rest/user/profile-update', accountManagement.updateProfile())",
  "  app.post('/rest/user/quick-reset', accountManagement.requestQuickReset())",
  "  app.post('/rest/user/quick-reset/confirm', accountManagement.confirmQuickReset())",
  "  app.get('/rest/user/audit-log', accountManagement.getAuditLog())",
  "  app.get('/rest/admin/service-status', adminDiagnostics.serviceStatus())",
  "  app.get('/rest/admin/user-stats', adminDiagnostics.userStats())",
  "  app.post('/rest/user/preferences/restore', dataImport.restorePreferences())",
  "  app.post('/rest/products/import-feed', dataImport.importProductFeed())",
  "  app.post('/rest/partner/verify-token', integrations.verifyPartnerToken())",
  "  app.post('/rest/notifications/preview', integrations.previewNotification())",
  "  app.get('/rest/promos/search', promotions.searchPromos())",
  "  app.get('/rest/promos/landing/:code', promotions.promoLanding())",
  "  app.post('/rest/promos/apply', promotions.applyPromo())",
  "  app.get('/rest/promos/active', promotions.listActivePromos())",
  "  app.get('/rest/promos/analytics/:code', promotions.getPromoAnalytics())",
  "  app.post('/rest/coupons/lookup', couponManager.lookupCoupon())",
  "  app.get('/rest/coupons/:id', couponManager.getCoupon())",
  "  app.post('/rest/coupons/validate', couponManager.validateCoupon())",
  "  app.get('/rest/coupons/category', couponManager.listByCategory())",
  "  app.get('/rest/coupons/attempts/:code', couponManager.getCouponAttempts())",
  "  app.post('/rest/gift-cards/redeem', giftCards.redeemGiftCard())",
  "  app.post('/rest/gift-cards/:id/messages', giftCards.postGiftMessage())",
  "  app.get('/rest/gift-cards/:id/messages', giftCards.viewGiftMessage())",
  "  app.post('/rest/gift-cards/configure', giftCards.configureGiftCard())",
  "  app.get('/rest/gift-cards/:code/history', giftCards.getRedemptionHistory())",
  "  app.get('/rest/wishlists/search', wishlist.searchWishlists())",
  "  app.get('/rest/wishlists/:id', wishlist.getWishlist())",
  "  app.put('/rest/wishlists/:id/shipping', wishlist.updateShipping())",
  "  app.get('/rest/wishlists/:id/shipping-config', wishlist.getShippingConfig())",
  "  app.post('/rest/wishlists/:id/items', wishlist.addItem())",
  "  app.get('/rest/shipping/rate', shippingCalculator.getRate())",
  "  app.post('/rest/shipping/calculate', shippingCalculator.calculateShipping())",
  "  app.get('/rest/shipping/zones', shippingCalculator.loadZone())",
  "  app.get('/rest/shipping/zones/list', shippingCalculator.listZones())",
  "  app.get('/rest/shipping/carriers', shippingCalculator.listCarriers())",
  "  app.get('/rest/returns/policy', returnProcessor.fetchPolicy())",
  "  app.get('/rest/returns/search', returnProcessor.searchReturns())",
  "  app.get('/rest/returns/confirm/:orderId', returnProcessor.returnConfirmation())",
  "  app.get('/rest/returns/policy/cached', returnProcessor.getCachedPolicy())",
  "  app.get('/rest/returns/reasons', returnProcessor.listReturnReasons())",
  "  app.get('/rest/affiliate/click', affiliateTracker.recordClick())",
  "  app.get('/rest/affiliate/stats', affiliateTracker.affiliateStats())",
  "  app.get('/rest/affiliate/leaderboard', affiliateTracker.leaderboard())",
  "  app.post('/rest/vendor/login', vendorPortal.vendorLogin())",
  "  app.post('/rest/vendor/soap-update', vendorPortal.processSoapUpdate())",
  "  app.get('/rest/vendor/invoice', vendorPortal.fetchInvoice())",
  "  app.post('/rest/tax/calculate', taxCalculator.calculateTax())",
  "  app.get('/rest/tax/lookup', taxCalculator.lookupTaxRate())",
  "  app.get('/rest/tax-rates/search', taxCalculator.searchTaxRates())",
  "  app.put('/rest/loyalty/:id', loyaltyPoints.updateAccount())",
  "  app.post('/rest/loyalty/transfer', loyaltyPoints.transferPoints())",
  "  app.post('/rest/loyalty/adjust', loyaltyPoints.addAdjustment())",
  "  app.post('/rest/search', searchIndex.searchIndex())",
  "  app.post('/rest/products/:id/annex-reviews', searchIndex.postReview())",
  "  app.get('/rest/products/:id/annex-reviews', searchIndex.viewReviews())",
  "  app.get('/rest/search/synonyms', searchIndex.loadSynonyms())",
  "  app.get('/rest/search/raw-lookup', searchIndex.rawLookup())",
  "  app.post('/rest/cart/discount-preview', cartDiscounts.previewDiscount())",
  "  app.post('/rest/cart/best-discount', cartDiscounts.applyBestDiscount())",
  "  app.get('/rest/cart/rules/search', cartDiscounts.searchRules())",
  "  app.post('/rest/notifications/send', notificationsApi.sendNotification())",
  "  app.get('/rest/notifications/:id', notificationsApi.getNotification())",
  "  app.post('/rest/notifications/graphql', notificationsApi.graphqlQuery())",
  "  app.get('/rest/admin/reports/generate', adminReports.generateReport())",
  "  app.get('/rest/admin/reports/search', adminReports.searchReports())",
  "  app.get('/rest/admin/reports/verify', adminReports.verifyAdminKey())",
  "  app.get('/rest/admin/reports/download', adminReports.downloadReport())",
  "  app.post('/rest/mobile/session', mobileApi.verifySession())",
  "  app.get('/rest/mobile/profile/:id', mobileApi.getProfile())",
  "  app.get('/rest/mobile/image', mobileApi.proxyImage())",
  "  app.get('/rest/feedback/export', feedbackCollector.exportCsv())",
  "  app.post('/rest/feedback/xml', feedbackCollector.parseXmlFeedback())",
  "  app.post('/rest/feedback/:product', feedbackCollector.submitFeedback())",
  "  app.get('/rest/feedback/:product', feedbackCollector.viewFeedback())",
  "  app.post('/rest/inventory/verify-password', inventoryManager.verifyPassword())",
  "  app.get('/rest/inventory/details', inventoryManager.inventoryDetails())",
  "  app.post('/rest/inventory/filter', inventoryManager.filterInventory())",
  "  app.get('/rest/prices/token', priceTracker.generateToken())",
  "  app.get('/rest/prices/lookup', priceTracker.lookupPrice())",
  "  app.get('/rest/prices/search', priceTracker.searchPrices())",
  "  app.get('/rest/orders/export', orderExport.exportOrders())",
  "  app.get('/rest/orders/all', orderExport.getAllOrders())",
  "  app.post('/rest/orders/verify-discount', orderExport.verifyDiscount())",
  "  app.post('/rest/session/login', sessionManager.login())",
  "  app.get('/rest/session/cookie', sessionManager.setSessionCookie())",
  "  app.post('/rest/session/reset-password', sessionManager.resetPassword())",
  "  app.get('/rest/content/include', contentManager.includeTemplate())",
  "  app.post('/rest/content/render', contentManager.renderContent())",
  "  app.get('/rest/content/asset', contentManager.readAsset())",
  "  app.post('/rest/analytics/event', analyticsTracker.recordEvent())",
  "  app.get('/rest/analytics/report', analyticsTracker.fetchReport())",
  "  app.get('/rest/analytics/pixel', analyticsTracker.trackingPixel())",
  "  app.post('/rest/reviews/xml', reviewModeration.parseXmlReview())",
  "  app.post('/rest/reviews/upload', reviewModeration.uploadAttachment())",
  "  app.post('/rest/reviews/metadata', reviewModeration.processMetadata())",
  "  app.get('/rest/support/cors', customerSupport.corsPreflight())",
  "  app.get('/rest/support/debug', customerSupport.getDebugInfo())",
  "  app.get('/rest/support/download', customerSupport.downloadAttachment())",
  "  app.delete('/rest/warehouse/:id', warehouseApi.deleteWarehouse())",
  "  app.get('/rest/warehouse/check-service', warehouseApi.checkService())",
  "  app.get('/rest/warehouse/info', warehouseApi.getWarehouseInfo())",
  "  app.get('/rest/billing/account/:id', billingPortal.getAccount())",
  "  app.put('/rest/billing/balance/:id', billingPortal.updateBalance())",
  "  app.get('/rest/billing/redirect', billingPortal.paymentRedirect())",
  "  app.post('/rest/subscriptions/restore', subscriptionManager.restoreBackup())",
  "  app.put('/rest/subscriptions/:id/quantity', subscriptionManager.updateQuantity())",
  "  app.get('/rest/audit/search', complianceAudit.searchAuditLogs())",
  "  app.post('/rest/audit/encrypt', complianceAudit.encryptRecord())",
  "  app.get('/rest/audit/:id', complianceAudit.getAuditLog())",
  "  app.get('/rest/stores/find', storeLocator.findStores())",
  "  app.get('/rest/stores/:id', storeLocator.getStoreDetails())",
  "  app.get('/rest/stores/:id/inventory', storeLocator.listStoreInventory())",
  "  app.get('/rest/stores/:id/hours', storeLocator.getStoreHours())",
  "  app.post('/rest/stores/:id/reserve', storeLocator.reserveProduct())",
  "  app.get('/rest/recipes/search', recipeFinder.searchRecipes())",
  "  app.get('/rest/recipes/:id', recipeFinder.getRecipe())",
  "  app.get('/rest/recipes/:id/nutrition', recipeFinder.getNutritionInfo())",
  "  app.post('/rest/recipes/:id/rate', recipeFinder.rateRecipe())",
  "  app.post('/rest/recipes/suggest', recipeFinder.suggestRecipe())",
  "  app.get('/rest/rewards/balance/:userId', loyaltyRewards.getPointsBalance())",
  "  app.post('/rest/rewards/redeem', loyaltyRewards.redeemReward())",
  "  app.get('/rest/rewards/catalog', loyaltyRewards.listRewardsCatalog())",
  "  app.get('/rest/rewards/history/:userId', loyaltyRewards.getRewardHistory())",
  "  app.post('/rest/rewards/transfer', loyaltyRewards.transferPoints())",
  "  app.get('/rest/billing2/plans/:userId', subscriptionBilling.getCurrentPlan())",
  "  app.post('/rest/billing2/plans/upgrade', subscriptionBilling.upgradePlan())",
  "  app.get('/rest/billing2/invoices/:userId', subscriptionBilling.getInvoiceHistory())",
  "  app.get('/rest/billing2/invoices/:userId/:invoiceId', subscriptionBilling.downloadInvoice())",
  "  app.put('/rest/billing2/payment-method', subscriptionBilling.updatePaymentMethod())",
  "  app.get('/rest/profiles/:userId', customerProfiles.getProfile())",
  "  app.put('/rest/profiles/:userId', customerProfiles.updateProfile())",
  "  app.get('/rest/profiles/:userId/preferences', customerProfiles.getPreferences())",
  "  app.put('/rest/profiles/:userId/preferences', customerProfiles.updatePreferences())",
  "  app.delete('/rest/profiles/:userId', customerProfiles.deleteProfile())",
  "  app.get('/rest/product-reviews/:productId', productReviews.getReviews())",
  "  app.post('/rest/product-reviews/:productId', productReviews.addReview())",
  "  app.put('/rest/product-reviews/:productId/:reviewId', productReviews.editReview())",
  "  app.delete('/rest/product-reviews/:productId/:reviewId', productReviews.deleteReview())",
  "  app.get('/rest/product-reviews/:productId/stats', productReviews.getReviewStats())",
  "  app.get('/rest/order-tracking/:orderId', orderTracking.trackOrder())",
  "  app.get('/rest/order-tracking/:orderId/status', orderTracking.getOrderStatus())",
  "  app.get('/rest/order-tracking/:orderId/timeline', orderTracking.getOrderTimeline())",
  "  app.post('/rest/order-tracking/:orderId/issue', orderTracking.reportIssue())",
  "  app.post('/rest/order-tracking/:orderId/refund', orderTracking.requestRefund())",
  "  app.post('/rest/wishlists2', wishlistManager.createWishlist())",
  "  app.get('/rest/wishlists2/:id', wishlistManager.getWishlist())",
  "  app.post('/rest/wishlists2/:id/items', wishlistManager.addItemToWishlist())",
  "  app.delete('/rest/wishlists2/:id/items/:itemId', wishlistManager.removeItemFromWishlist())",
  "  app.post('/rest/wishlists2/:id/share', wishlistManager.shareWishlist())",
  "  app.get('/rest/notifications2/:userId', notificationCenter.getNotifications())",
  "  app.put('/rest/notifications2/:userId/:notifId/read', notificationCenter.markAsRead())",
  "  app.put('/rest/notifications2/:userId/prefs', notificationCenter.updateNotificationPrefs())",
  "  app.post('/rest/notifications2/subscribe', notificationCenter.subscribeToTopic())",
  "  app.delete('/rest/notifications2/:userId/unsubscribe/:topic', notificationCenter.unsubscribeFromTopic())",
  "  app.get('/rest/inventory2/stock/:sku', inventoryCheck.checkStock())",
  "  app.get('/rest/inventory2/levels', inventoryCheck.getStockLevels())",
  "  app.post('/rest/inventory2/restock', inventoryCheck.requestRestock())",
  "  app.get('/rest/inventory2/restock/history/:sku', inventoryCheck.getRestockHistory())",
  "  app.post('/rest/inventory2/availability', inventoryCheck.checkAvailability())",
  "  app.get('/rest/promo-codes/active', promoCodes.listActivePromos())",
  "  app.post('/rest/promo-codes/validate', promoCodes.validatePromo())",
  "  app.get('/rest/promo-codes/:code', promoCodes.getPromoDetails())",
  "  app.post('/rest/promo-codes', promoCodes.createPromo())",
  "  app.put('/rest/promo-codes/:code/deactivate', promoCodes.deactivatePromo())",
  "  app.get('/rest/shipping2/zones', shippingZones.getShippingZones())",
  "  app.get('/rest/shipping2/zones/:zoneId/rate', shippingZones.getZoneRate())",
  "  app.post('/rest/shipping2/calculate', shippingZones.calculateShippingCost())",
  "  app.get('/rest/shipping2/estimate/:zoneId', shippingZones.getDeliveryEstimate())",
  "  app.get('/rest/shipping2/carriers', shippingZones.listCarriers())",
  "  app.post('/rest/returns2', returnsManager.createReturnRequest())",
  "  app.get('/rest/returns2/:returnId', returnsManager.getReturnStatus())",
  "  app.put('/rest/returns2/:returnId/approve', returnsManager.approveReturn())",
  "  app.post('/rest/returns2/:returnId/refund', returnsManager.processRefund())",
  "  app.get('/rest/returns2/history/:userId', returnsManager.getReturnHistory())",
  "  app.post('/rest/vendors/register', vendorManagement.registerVendor())",
  "  app.get('/rest/vendors/:vendorId', vendorManagement.getVendorProfile())",
  "  app.put('/rest/vendors/:vendorId', vendorManagement.updateVendorProfile())",
  "  app.get('/rest/vendors/:vendorId/products', vendorManagement.getVendorProducts())",
  "  app.get('/rest/vendors/:vendorId/orders', vendorManagement.getVendorOrders())",
  "  app.post('/rest/support2/tickets', customerSupport2.createTicket())",
  "  app.get('/rest/support2/tickets/:ticketId', customerSupport2.getTicket())",
  "  app.post('/rest/support2/tickets/:ticketId/replies', customerSupport2.replyToTicket())",
  "  app.put('/rest/support2/tickets/:ticketId/close', customerSupport2.closeTicket())",
  "  app.get('/rest/support2/categories', customerSupport2.listTicketCategories())",
  "  app.get('/rest/analytics2/sales', analyticsDashboard.getSalesSummary())",
  "  app.get('/rest/analytics2/top-products', analyticsDashboard.getTopProducts())",
  "  app.get('/rest/analytics2/revenue/categories', analyticsDashboard.getRevenueByCategory())",
  "  app.get('/rest/analytics2/customers', analyticsDashboard.getCustomerMetrics())",
  "  app.get('/rest/analytics2/export', analyticsDashboard.exportDashboard())",
  "  app.get('/rest/price-manager/:sku', priceManager.getPrice())",
  "  app.put('/rest/price-manager/:sku', priceManager.updatePrice())",
  "  app.get('/rest/price-manager/:sku/history', priceManager.getPriceHistory())",
  "  app.post('/rest/price-manager/bulk', priceManager.bulkUpdatePrices())",
  "  app.get('/rest/price-manager/:sku/compare', priceManager.getPriceComparison())",
  "  app.get('/rest/pages/:slug', contentPages.getPage())",
  "  app.get('/rest/pages', contentPages.listPages())",
  "  app.post('/rest/pages', contentPages.createPage())",
  "  app.put('/rest/pages/:slug', contentPages.updatePage())",
  "  app.delete('/rest/pages/:slug', contentPages.deletePage())",
  "  app.post('/rest/tax-exemptions', taxExemptions.submitExemption())",
  "  app.get('/rest/tax-exemptions/:exemptionId', taxExemptions.getExemptionStatus())",
  "  app.put('/rest/tax-exemptions/:exemptionId/verify', taxExemptions.verifyExemption())",
  "  app.get('/rest/tax-exemptions', taxExemptions.listExemptions())",
  "  app.delete('/rest/tax-exemptions/:exemptionId', taxExemptions.revokeExemption())",
  "  app.post('/rest/gift-registry', giftCardRegistry.createGiftCard())",
  "  app.get('/rest/gift-registry/:code', giftCardRegistry.getGiftCard())",
  "  app.get('/rest/gift-registry/:code/balance', giftCardRegistry.checkBalance())",
  "  app.post('/rest/gift-registry/:code/redeem', giftCardRegistry.redeemGiftCard())",
  "  app.get('/rest/gift-registry/:code/transactions', giftCardRegistry.listGiftCardTransactions())"
];

// 1. Copy the modules into the repo
for (const m of MODULES) fs.copyFileSync(path.join(__dirname, 'routes', `${m}.ts`), path.join(routesDir, `${m}.ts`));
console.log(`✓ ${MODULES.length} route modules written to routes/`);

// 2. Wire them into server.ts (idempotent)
let src = fs.readFileSync(serverPath, 'utf8');
let changed = false;
if (!src.includes("from './routes/productCatalog'")) {
  const lines = src.split('\n');
  let idx = -1;
  lines.forEach((l, i) => { if (l.includes("from './routes/")) idx = i; });
  if (idx === -1) { console.error('Could not find route imports in server.ts'); process.exit(1); }
  lines.splice(idx + 1, 0, IMPORTS.join('\n'));
  src = lines.join('\n');
  changed = true;
  console.log('✓ imports added to server.ts');
} else { console.log('· imports already present'); }

if (!src.includes("'/rest/products/by-tag'")) {
  const anchor = '  /* Serve metrics before the Angular catch-all';
  if (!src.includes(anchor)) { console.error('Could not find mount anchor in server.ts'); process.exit(1); }
  src = src.replace(anchor, MOUNTS.join('\n') + '\n\n' + anchor);
  changed = true;
  console.log('✓ route mounts added to server.ts');
} else { console.log('· route mounts already present'); }
if (changed) fs.writeFileSync(serverPath, src);

// 3. Install dependencies and recompile the server
console.log('\nInstalling better-sqlite3...');
execSync('npm install better-sqlite3 --ignore-scripts', { cwd: dir, stdio: 'inherit' });
execSync('npm rebuild better-sqlite3', { cwd: dir, stdio: 'inherit' });
console.log('\nInstalling ejs...');
execSync('npm install ejs', { cwd: dir, stdio: 'inherit' });
console.log('\nRecompiling server...');
execSync('npm run build:server', { cwd: dir, stdio: 'inherit' });

console.log('\n✅ Done. Start Juice Shop with `npm start`, then target http://localhost:3000.');
console.log('   Verify:  BASE_URL=http://localhost:3000 node exploit-tests.js');
